import Head from 'next/head'
import Link from 'next/link'
import { getCsrfToken } from 'next-auth/react'
import { getMessages } from '@/i18n'
import { useTranslations } from 'next-intl'

export default function Home(props: any) {
  const t = useTranslations('Index')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          {t('title')} - {props.locale}
        </h1>

        <div className="flex flex-col spacy-y-3">
          <Link href="/" locale="en">
            US
          </Link>
          <Link href="/" locale="sv">
            SV
          </Link>

          <Link href="/dashboard">Dashboard</Link>
          <Link href="/login">Login</Link>

          <form action="/api/auth/signout" method="POST">
            <input type="hidden" name="csrfToken" value={props.token} />
            <button type="submit">Sign out</button>
          </form>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps({ locale, req }: any) {
  const token = await getCsrfToken({ req })

  return {
    props: {
      locale,
      token,
      messages: await getMessages(locale, ['Index', 'Components']),
    },
  }
}
